---
site_name: aioswitcher
site_url: https://aioswitcher.tomfi.info
site_author: Tomer Figenblat
site_description: PyPi module integrating with various Switcher devices.

repo_name: TomerFi/aioswitcher
repo_url: https://github.com/TomerFi/aioswitcher
edit_uri: ""

nav:
  - Home: index.md
  - Install: install.md
  - Usage:
      - Bridge: usage_bridge.md
      - API: usage_api.md
  - Supported devices: supported.md
  - Code documentation: codedocs.md
  - Helper scripts: scripts.md

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: ["docs"]
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: ⚓︎

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TomerFi
      name: TomerFi on GitHub
    - icon: fontawesome/brands/dev
      link: https://dev.to/tomerfi
      name: tomerfi on Dev.to
    - icon: fontawesome/brands/redhat
      link: https://developers.redhat.com/author/tomerfi
      name: tomerfi on Red Hat Developer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tomerfi/
      name: tomerfi on LinkedIn
  analytics:
    provider: google
    property: G-8965F1P656

plugins:
  - search
  - git-revision-date
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            filters:
              - "!^_"
            summary:
              attributes: false
              functions: true
              modules: true

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  font:
    code: Fira Code
    text: Open Sans
  palette:
    - media: "(prefers-color-scheme)"
      primary: red
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      primary: red
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
